package dev.rubentxu.pipeline.fabric.consumer

import dev.rubentxu.pipeline.v2.domain.FailureKind
import dev.rubentxu.pipeline.v2.domain.PipelineFailure
import dev.rubentxu.pipeline.v2.domain.RunOutcome
import dev.rubentxu.pipeline.v2.events.identity.EventCursor
import dev.rubentxu.pipeline.v2.events.identity.EventQuery
import dev.rubentxu.pipeline.v2.events.identity.PipelineEventEnvelope
import dev.rubentxu.pipeline.v2.events.identity.PipelineEventEnvelopeSerializer
import dev.rubentxu.pipeline.v2.output.OutputCursor
import dev.rubentxu.pipeline.v2.output.OutputReadPort
import dev.rubentxu.pipeline.v2.output.OutputReadResult
import dev.rubentxu.pipeline.v2.output.OutputRefusal
import dev.rubentxu.pipeline.v2.output.OutputStreamId
import kotlinx.serialization.json.Json
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertInstanceOf
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.nio.charset.StandardCharsets

/**
 * The golden contract, asserted from OUTSIDE the product.
 *
 * BLOCK 2 requires versioned golden contracts for the four run outcomes, for event paging and for
 * output paging and refusals. This is where they live, and the choice of file is the point: a golden
 * that lived inside `v2` would be regenerated by the same commit that changed the contract, and a
 * reviewer would be comparing a file with itself. Here the expected text is committed in a
 * repository that has no access to the product's sources, so a change to the published shape fails
 * a build that never saw the change.
 */
class FabricGoldenContractTest {

    private val golden: String =
        javaClass.getResourceAsStream("/golden/contracts.golden")!!.readBytes().decodeToString()

    /**
     * Every row is `<name> = <value>`, and the file is compared WHOLE.
     *
     * Whole-file rather than row by row, so a REMOVED row cannot pass unnoticed: a comparison that
     * only looks up the rows it already knows about would keep reporting success after the contract
     * shed a case, and the golden would have quietly become a subset of itself.
     */
    private fun assertGolden(rows: List<Pair<String, String>>) {
        val expected = rows.map { (name, value) -> "$name = $value" }.sorted().joinToString("\n")
        assertEquals(
            expected,
            golden.trim(),
            "the published contract no longer matches its golden. A consumer written against the " +
                "old shape is now wrong, and this repository cannot see the code that changed it.",
        )
    }

    /**
     * The one row that pins the contract, and the only place `assertGolden` is called.
     *
     * Comparing the whole file from a single call is what makes a REMOVED row fail. Four tests each
     * passing their own subset is the version that shipped first, and it was broken in the direction
     * that hides things: every subset matched its own rows and reported the whole file as different,
     * so the interesting signal — "a case is gone" — was indistinguishable from "a test is wrong".
     *
     * Every case of every closed algebra this consumer maps is a row here: four run outcomes, six
     * refusals, five event queries. A row for a case that stops existing makes this test fail, which
     * is the only moment a consumer learns its mapping went stale.
     */
    @Test
    fun `the published contract matches its golden, in full`() {
        val known = OutputStreamId("run-42/step-0/transcript")
        val other = OutputStreamId("run-99/step-7/transcript")
        val sample = envelope(kind = "StepFinished", sequence = 3)
        val json = Json { encodeDefaults = true }
        val eventCursor = EventCursor("v1:pipeline:run-42", 7L)
        val outputCursor = OutputCursor(known, 128L)

        assertGolden(
            buildList {
                add("outcome.RunOutcome.Success" to RunOutcome.Success.verdict().label)
                add("outcome.RunOutcome.Unstable" to RunOutcome.Unstable.verdict().label)
                add(
                    "outcome.RunOutcome.Failure" to
                        RunOutcome.Failure(
                            PipelineFailure(kind = FailureKind.SCRIPT, message = "core.sh exited with code 1"),
                        ).verdict().label,
                )
                add("outcome.RunOutcome.Aborted" to RunOutcome.Aborted.verdict().label)

                add("refusal.ForeignStream" to explain(OutputRefusal.ForeignStream(known, other)))
                add("refusal.UnknownStream" to explain(OutputRefusal.UnknownStream(other)))
                add(
                    "refusal.OffsetBeyondCommitted" to
                        explain(OutputRefusal.OffsetBeyondCommitted(requested = 9, committed = 2)),
                )
                add("refusal.InvalidRange" to explain(OutputRefusal.InvalidRange(5, 5)))
                add("refusal.RecoveryNotCompleted" to explain(OutputRefusal.RecoveryNotCompleted))
                add(
                    "refusal.DanglingCommit" to
                        explain(OutputRefusal.DanglingCommit(requestedEnd = 9, readableBytes = 2)),
                )

                add("cursor.output.token" to outputCursor.encode())
                add("cursor.event.token" to eventCursor.encode())

                add("query.All" to EventQuery.All.describe())
                add("query.ByKind" to EventQuery.ByKind("StepFinished").describe())
                add("query.BySource" to EventQuery.BySource(demoRun).describe())
                add("query.BySubject" to EventQuery.BySubject(demoRun).describe())
                add("query.BySequenceRange" to EventQuery.BySequenceRange(1, 9).describe())

                add("envelope.version" to sample.version.toString())
                add("envelope.json" to json.encodeToString(PipelineEventEnvelopeSerializer, sample))
                add("envelope.causation" to sample.causation?.id?.value.orEmpty())
                add("envelope.correlation" to sample.correlation?.id?.value.orEmpty())
            },
        )
    }

    // ------------------------------------------------------------------ run outcomes

    @Test
    fun `the four run outcomes map to the four verdicts a build status can show`() {
        // Every case is constructed here from the published type. A fifth outcome added to the
        // algebra would break `verdict()` at compile time in this build, which is the intended
        // signal and not a test failure to work around.
        val success = RunOutcome.Success.verdict()
        val unstable = RunOutcome.Unstable.verdict()
        val failure = RunOutcome.Failure(PipelineFailure(kind = FailureKind.SCRIPT, message = "core.sh exited with code 1")).verdict()
        val aborted = RunOutcome.Aborted.verdict()

        assertEquals(RunVerdict.Passed, success)
        assertEquals(RunVerdict.Flaky, unstable)
        assertEquals(RunVerdict.Failed, failure)
        assertEquals(RunVerdict.Cancelled, aborted)

        // Distinct verdicts AND distinct labels, because a consumer sends both: the verdict to its
        // own state machine, the label to a human. Two cases sharing a label would render two
        // different runs identically on a Jenkins page while still behaving differently underneath.
        val labels = listOf(success, unstable, failure, aborted).map { it.label }
        assertEquals(labels.size, labels.distinct().size, "each verdict must carry its own label: $labels")
    }

    // ------------------------------------------------------------------ output paging

    @Test
    fun `a console reassembles a transcript byte for byte by following the page cursor`() {
        val stream = OutputStreamId("run-42/step-0/transcript")
        val text = "line one\nline two\nline three\n"
        val console = InMemoryConsole(transcript(stream, text))

        // A page of 8 bytes over a 27-byte transcript forces four round trips, so a loop that
        // stopped early or dropped a page would be caught here rather than in a console.
        val (read, stop) = readConsole(console, stream, maxBytesPerPage = 8)

        assertEquals(text, read, "paging must reassemble the transcript byte for byte")
        assertEquals(ConsoleReadStop.Ended(text.length.toLong()), stop)
    }

    @Test
    fun `a stream with no committed bytes ends rather than refusing`() {
        val stream = OutputStreamId("run-42/step-0/transcript")
        val console = InMemoryConsole(transcript(stream, ""))

        val (read, stop) = readConsole(console, stream)

        assertEquals("", read, "a stream with no committed bytes reads as no text")
        assertEquals(
            ConsoleReadStop.Ended(0L),
            stop,
            "zero committed bytes is an end of the page sequence, not a refusal",
        )
    }

    // ------------------------------------------------------------------ output refusals

    @Test
    fun `every refusal reaches the caller as a nameable value rather than an empty page`() {
        val known = OutputStreamId("run-42/step-0/transcript")
        val other = OutputStreamId("run-99/step-7/transcript")

        // Each row drives the contract through the PORT, not through a helper, so what is pinned is
        // the behaviour a consumer actually gets. An empty page would satisfy a length assertion
        // while hiding every one of these, which is the failure the closed ADT exists to prevent.
        assertEquals(
            "no stream ${other.value}",
            readConsole(InMemoryConsole(transcript(known, "bytes\n")), other).second.refusalReason(),
        )

        val fresh = InMemoryConsole(transcript(known, "bytes\n"))
        assertEquals(
            "cursor belongs to $other, not $known",
            singleRead(fresh, known, OutputCursor(other, 0L)),
            "a cursor naming another stream is a real consumer mistake and must be refused, not clamped",
        )

        assertEquals(
            "offset 999 is past the committed end 6",
            singleRead(InMemoryConsole(transcript(known, "bytes\n")), known, OutputCursor(known, 999L)),
        )

        val unrecovered = InMemoryConsole(transcript(known, "bytes\n"))
        unrecovered.recoveryGate = OutputRefusal.RecoveryNotCompleted
        assertEquals(
            "the store has not finished recovery",
            readConsole(unrecovered, known).second.refusalReason(),
        )

        // The two range refusals, reached through readRange rather than read. Both were wrong in
        // this file's first version, in the direction that hides a lie: a range past the committed
        // end was assumed to be a DanglingCommit, and the in-memory port quietly truncated. The
        // published law is OffsetBeyondCommitted for a range the store cannot serve, and
        // DanglingCommit is a different thing entirely — see the test below.
        val ranged = InMemoryConsole(transcript(known, "bytes\n"))
        assertEquals(
            "range [9, 5) is not a forward range",
            singleReadRange(ranged, known, from = 9, to = 5),
            "an inverted range is a caller bug, and it must be named rather than read as empty",
        )
        assertEquals(
            "offset 9 is past the committed end 6",
            singleReadRange(ranged, known, from = 0, to = 9),
            "a range past the committed end is refused, never truncated to what happens to be there",
        )
        assertEquals("bytes\n", singleReadRange(ranged, known, from = 0, to = 6), "the in-range read still works")
    }

    @Test
    fun `a dangling commit is a store integrity failure a correct port cannot produce`() {
        // Six refusals exist, and this is the one a consumer will never see from a well-behaved
        // implementation. DanglingCommit means the store's committed extent claimed an end it could
        // not serve: the offset is inside the committed range, yet fewer bytes came back. An
        // in-memory port cannot reach that state without lying about its own size, which is why
        // this row asserts the NON-reachability rather than manufacturing the condition.
        //
        // It is pinned here because a Fabric adapter must still name it. It is the shape a real
        // store reaches when its journal and its segments disagree after a crash, and an adapter
        // with no branch for it would fall through to "empty console" on precisely the run whose
        // output is known to be corrupt.
        val known = OutputStreamId("run-42/step-0/transcript")
        val console = InMemoryConsole(transcript(known, "bytes\n"))

        for (from in 0L..6L) {
            for (to in 0L..9L) {
                val outcome = console.readRange(known, from, to)
                val isDangling = outcome is OutputReadResult.Refused &&
                    outcome.reason is OutputRefusal.DanglingCommit
                assertTrue(
                    !isDangling,
                    "a port whose committed extent equals its byte count must never report a " +
                        "dangling commit, but readRange($from, $to) produced $outcome",
                )
            }
        }

        // Named all the same, because the branch exists in the consumer whether or not this
        // particular port can reach it.
        assertEquals(
            "2 readable bytes back a commit claiming 9",
            explain(OutputRefusal.DanglingCommit(requestedEnd = 9, readableBytes = 2)),
        )
    }

    @Test
    fun `the refusal vocabulary is closed and every case is nameable`() {
        val known = OutputStreamId("run-42/step-0/transcript")
        val other = OutputStreamId("run-99/step-7/transcript")

        // Every case of the closed ADT, named through the consumer's own `explain`. A seventh case
        // breaks `explain` at compile time here, which is the intended signal: a consumer must be
        // TOLD that a new reason exists, not discover it as an unhandled branch on a user's console.
        val named = listOf(
            OutputRefusal.ForeignStream(expected = known, actual = other),
            OutputRefusal.UnknownStream(other),
            OutputRefusal.OffsetBeyondCommitted(requested = 9, committed = 2),
            OutputRefusal.InvalidRange(5, 5),
            OutputRefusal.RecoveryNotCompleted,
            OutputRefusal.DanglingCommit(requestedEnd = 9, readableBytes = 2),
        ).map(::explain)

        // Distinct, and none of them empty. Two cases collapsing onto one message is the specific
        // failure this vocabulary exists to rule out: the operator sees one sentence for two
        // different faults and cannot tell which one to chase.
        assertEquals(named.size, named.distinct().size, "two refusals share a message: $named")
        assertTrue(named.none { it.isBlank() }, "a refusal with no text tells an operator nothing: $named")
    }

    // ------------------------------------------------------------------ cursors and events

    @Test
    fun `the two cursor wire formats stay distinct`() {
        // Two prefixes, two planes. A consumer that pasted an event cursor where an output cursor
        // belongs gets a decode failure rather than a plausible offset into the wrong bytes.
        val output = OutputCursor(OutputStreamId("run-42/step-0/transcript"), 128L)
        val event = EventCursor("v1:pipeline:run-42", 7L)

        // The run id is percent-escaped, because it CONTAINS colons: `ResourceRef.canonicalText()`
        // is `v<version>:<kind>:<segments>`. The token below is the one a real producer emits; the
        // unescaped spelling is exactly what the product used to hand out and its own decoder
        // rejected, so this literal is the regression this row guards.
        assertEquals("evt-cursor-v1:v1%3Apipeline%3Arun-42:7", event.encode())
        assertEquals("out-cursor-v1:run-42%2Fstep-0%2Ftranscript:128", output.encode())

        assertNull(OutputCursor.decode(event.encode()), "an event cursor must not decode as an output cursor")
        assertNull(EventCursor.decode(output.encode()), "an output cursor must not decode as an event cursor")
        assertEquals(output, OutputCursor.decode(output.encode()))
        assertEquals(event, EventCursor.decode(event.encode()))

        // The same round trip over the run id a real producer builds, rather than a hand-written
        // one. This is the path that failed: the literal above is what `demoRun.canonicalText()`
        // yields, and it contains the colons the first decoder counted.
        val real = EventCursor(demoRun.canonicalText(), 11L)
        assertEquals(real, EventCursor.decode(real.encode()), "a produced run id must survive its own token")

        // A truncated or over-long token is refused rather than partially read, so a corrupt
        // continuation cannot resume a run at a guessed sequence.
        assertNull(EventCursor.decode("evt-cursor-v1:v1%3Apipeline:7:extra"))
        assertNull(EventCursor.decode("evt-cursor-v1:"))
        assertNull(EventCursor.decode("evt-cursor-v1:%20:7"), "a blank run id is not a run")
        assertNull(EventCursor.decode("evt-cursor-v1:run:seven"), "a non-numeric sequence is refused")
    }

    @Test
    fun `history is walked to its end by following the continuation cursor`() {
        val history = demoHistory()
        val steps = readHistory(InMemoryHistory(history), demoRun)

        assertEquals(listOf("RunStarted", "StepStarted", "StepFinished"), steps.map { it.kind })
        assertEquals(listOf(1L, 2L, 3L), steps.map { it.sequence })

        // Paging one envelope at a time forces three round trips, which is what a reconnecting
        // observer does. A loop that stopped on an empty page, or trusted `hasMore` without the
        // cursor, would lose envelopes here.
        var cursor: EventCursor? = null
        val seen = mutableListOf<Long>()
        var pages = 0
        while (true) {
            val page = InMemoryHistory(history).readAfter(demoRun, cursor, limit = 1)
            pages++
            seen += page.envelopes.map { it.sequence }
            if (!page.hasMore) break
            cursor = requireNotNull(page.nextCursor) { "hasMore with no cursor is not a contract state" }
        }
        assertEquals(listOf(1L, 2L, 3L), seen, "paging one at a time still yields the whole history")
        assertEquals(3, pages, "the history took one page per envelope, so the cursor was followed")
    }

    @Test
    fun `an exhausted history ends without claiming the run is complete`() {
        // A run whose next stage has not emitted yet returns zero events. `hasMore = false` here
        // means "no more envelopes right now", NOT "the run finished": absence of RunFinished is
        // not completeness, and a Fabric stage view that collapses the two would render a live
        // build as a finished one. The consumer is only able to hold that distinction because the
        // published page says nothing about run completion at all.
        val page = InMemoryHistory(emptyList()).readAfter(demoRun, cursor = null, limit = 100)

        assertEquals(emptyList<Any>(), page.envelopes)
        assertEquals(false, page.hasMore, "an empty history reports no further envelopes")
        assertNull(page.nextCursor, "only a page that reached the end offers no continuation")
    }

    @Test
    fun `the envelope survives a round trip through the published serializer`() {
        // This row is what proves the POM carries kotlinx-serialization at COMPILE scope. The
        // consumer asks for four coordinates and names a KSerializer without knowing that
        // `kotlinx-serialization-json` is a dependency at all; under `implementation` scope in the
        // publisher, this line would not compile.
        val original = envelope(kind = "StepFinished", sequence = 3)
        val json = Json { encodeDefaults = true }

        val encoded = json.encodeToString(PipelineEventEnvelopeSerializer, original)
        val decoded = json.decodeFromString(PipelineEventEnvelopeSerializer, encoded)

        assertEquals(original, decoded, "an envelope must survive its own wire form unchanged")
        assertEquals(PipelineEventEnvelope.VERSION, original.version, "the envelope declares its own version")
        assertEquals("evt-1", original.correlation?.id?.value, "correlation is reachable from outside")
        assertEquals("evt-2", original.causation?.id?.value, "causation is reachable from outside")

        // Causation and correlation must be in the WIRE text, not merely readable off the object
        // after construction. They were declared on `Wire`, absent from `serialize`, and asserted
        // in this file's own KDoc; a consumer that parsed the JSON had no causal context at all.
        assertTrue(encoded.contains("\"causation\""), "causation is missing from the wire form: $encoded")
        assertTrue(encoded.contains("\"correlation\""), "correlation is missing from the wire form: $encoded")
    }

    @Test
    fun `the event query algebra is closed over the consumer side too`() {
        val named = listOf(
            EventQuery.All,
            EventQuery.ByKind("StepFinished"),
            EventQuery.BySource(demoRun),
            EventQuery.BySubject(demoRun),
            EventQuery.BySequenceRange(1, 9),
        ).map { it.describe() }

        // Exhaustive in `describe()`: a sixth case breaks this file's own list construction at
        // compile time only if `describe` stops being exhaustive. What is asserted here is the
        // runtime half, which the compiler cannot check — that the five are distinguishable.
        assertEquals(named.size, named.distinct().size, "two queries describe identically: $named")
        assertTrue(named.none { it.isBlank() }, "a query with no description is unloggable: $named")

        // BySource and BySubject carry the same reference here, so they must still differ: they
        // ask different questions of the store, and a log that cannot tell them apart is a log
        // that cannot be read back.
        assertEquals("source=${demoRun.canonicalText()}", EventQuery.BySource(demoRun).describe())
        assertEquals("subject=${demoRun.canonicalText()}", EventQuery.BySubject(demoRun).describe())
    }

    /** One page read, returning the refusal text. Keeps the refusal rows about the port, not plumbing. */
    private fun singleRead(
        console: OutputReadPort,
        stream: OutputStreamId,
        cursor: OutputCursor,
    ): String = when (val result = console.read(stream, cursor, 1024)) {
        is OutputReadResult.Refused -> explain(result.reason)
        is OutputReadResult.Page -> String(result.page.bytes, StandardCharsets.UTF_8)
    }

    /** The same, for the ranged entry point. */
    private fun singleReadRange(
        console: OutputReadPort,
        stream: OutputStreamId,
        from: Long,
        to: Long,
    ): String = when (val result = console.readRange(stream, from, to)) {
        is OutputReadResult.Refused -> explain(result.reason)
        is OutputReadResult.Page -> String(result.page.bytes, StandardCharsets.UTF_8)
    }

    private fun ConsoleReadStop.refusalReason(): String =
        assertInstanceOf(ConsoleReadStop.Refused::class.java, this, "expected a refusal, got $this").reason
}
