package dev.rubentxu.pipeline.v2.credentials.api

import dev.rubentxu.pipeline.v2.domain.SecretHandle
import java.util.Base64
import java.util.regex.Pattern

/**
 * Registry for secret patterns used by [RedactingEventSink] to scrub secrets
 * from free-text event fields.
 *
 * ## Multi-form Pattern Generation
 *
 * Each registered secret generates patterns for multiple encodings:
 * - Literal: the raw secret bytes as UTF-8
 * - base64 std: Base64 standard encoder (with padding)
 * - base64 url-safe: Base64 URL-safe encoder (no padding)
 * - base64 trimmed padding/last-char: GitHub Actions runner#291 pattern
 * - hex upper: uppercase hex (2 chars per byte)
 * - hex lower: lowercase hex (2 chars per byte)
 * - URL-encoded: percent-encoded special chars
 *
 * ## Single Generation Seam
 *
 * All literal variants are generated by [generateEncodedVariants] and fed to
 * both [buildActivePatterns] (for scrub) and [maxPatternLength] (for carry-window
 * computation). This ensures consistent enumeration without duplication.
 *
 * ## Minimum Maskable Length
 *
 * Per GitLab rule, secrets shorter than 8 characters are NOT registered
 * for masking. They emit [SecretShorterThanMinimumMaskableLengthWarning] instead.
 *
 * ## Performance
 *
 * - Naive [Pattern.quote] alternation for ≤ 20 active secrets
 * - Aho-Corasick single-pass for > 20 secrets (switch in [RedactingEventSink])
 *
 * @see RedactingEventSink for the decorator that applies these patterns
 */
class SecretPatternRegistry {

    private val registeredSecrets = mutableSetOf<String>()

    /**
     * Registers a secret for masking.
     *
     * @param handle The [SecretHandle] wrapping the secret bytes
     * @throws SecretShorterThanMinimumMaskableLengthWarning if secret is below minimum length
     */
    fun addSecret(handle: SecretHandle) {
        val secretValue = handle.use { bytes ->
            String(bytes, Charsets.UTF_8)
        }

        if (secretValue.length < MIN_MASKABLE_LENGTH) {
            // Short secrets are not registered — emit warning handled by caller
            return
        }

        registeredSecrets.add(secretValue)
    }

    /**
     * Removes a secret from the registry.
     *
     * @param handle The [SecretHandle] wrapping the secret bytes
     */
    fun removeSecret(handle: SecretHandle) {
        val secretValue = handle.use { bytes ->
            String(bytes, Charsets.UTF_8)
        }
        registeredSecrets.remove(secretValue)
    }

    /**
     * Generates all encoded variants for a single secret.
     *
     * This is the SINGLE generation seam — feeds both [buildActivePatterns]
     * and [maxPatternLength] to ensure consistent enumeration.
     *
     * Variants generated (same set for both paths):
     * 1. Literal
     * 2. base64 std (with padding)
     * 3. base64 url-safe (no padding)
     * 4. base64 trimmed padding variants (GitHub runner#291)
     * 5. hex upper
     * 6. hex lower
     * 7. URL-encoded (only if secret contains chars needing encoding)
     *
     * @param secret The secret string to encode
     * @return List of all encoded variant strings
     */
    private fun generateEncodedVariants(secret: String): List<String> {
        val variants = mutableListOf<String>()
        val rawBytes = secret.toByteArray(Charsets.UTF_8)

        // 1. Literal
        variants.add(secret)

        // 2. base64 std (with padding)
        val b64Std = Base64.getEncoder().encodeToString(rawBytes)
        variants.add(b64Std)

        // 3. base64 url-safe (no padding)
        variants.add(Base64.getUrlEncoder().withoutPadding().encodeToString(rawBytes))

        // 4. base64 trimmed padding variants (GitHub runner#291)
        if (b64Std.endsWith("==")) {
            variants.add(b64Std.removeSuffix("=="))   // -2 chars
            variants.add(b64Std.dropLast(2))           // same as above, explicit
        } else if (b64Std.endsWith("=")) {
            variants.add(b64Std.removeSuffix("="))     // -1 char
        }

        // 5. hex upper
        variants.add(rawBytes.joinToString("") { "%02X".format(it) })

        // 6. hex lower
        variants.add(rawBytes.joinToString("") { "%02x".format(it) })

        // 7. URL-encoded (only if secret contains chars needing encoding)
        val urlEncoded = buildUrlEncodedVariant(secret)
        if (urlEncoded.isNotEmpty() && urlEncoded != secret) {
            variants.add(urlEncoded)
        }

        return variants
    }

    /**
     * Builds the active list of [Regex] patterns for all registered secrets.
     *
     * Uses naive [Pattern.quote] alternation for ≤ 20 secrets.
     * For > 20 secrets, [RedactingEventSink] switches to Aho-Corasick.
     *
     * @return List of [Regex] patterns — empty if no secrets registered
     */
    internal fun buildActivePatterns(): List<Regex> {
        val seam = literalSeam()
        if (seam.isEmpty()) return emptyList()

        val patterns = mutableListOf<Regex>()
        for (literal in seam) {
            patterns.add(Pattern.quote(String(literal, Charsets.UTF_8)).toRegex())
        }
        return patterns
    }

    /**
     * Returns the ordered seam of encoded literal byte arrays, longest-first
     * with deterministic tie-break (lexicographic order of the UTF-8 representation).
     *
     * This is the SINGLE internal seam used by both [buildActivePatterns] (for scrub)
     * and [StreamingRedactor] (for byte-level streaming match). No duplication.
     *
     * @return Ordered list of literal byte arrays, never empty (may return a
     *         single-item list containing only the UTF-8 bytes of [SCRUB_MARKER]
     *         when no secrets are registered, preserving the longest-first invariant)
     */
    internal fun literalSeam(): List<ByteArray> {
        if (registeredSecrets.isEmpty()) {
            // Return a sentinel that cannot match any real data — the marker itself
            // has length 4, which is shorter than any real pattern (min is hex-16 for 8-byte secret).
            // This keeps maxLiteralByteLength correct even when no secrets exist.
            return listOf(SCRUB_MARKER.toByteArray(Charsets.UTF_8))
        }

        val seam = mutableListOf<ByteArray>()
        for (secret in registeredSecrets) {
            for (variant in generateEncodedVariants(secret)) {
                seam.add(variant.toByteArray(Charsets.UTF_8))
            }
        }

        // Sort longest-first; tie-break by lexicographic byte order for determinism
        seam.sortWith(
            compareByDescending<ByteArray> { it.size }
                .thenComparator { a, b ->
                    val minLen = minOf(a.size, b.size)
                    for (i in 0 until minLen) {
                        val diff = (a[i].toInt() and 0xFF) - (b[i].toInt() and 0xFF)
                        if (diff != 0) return@thenComparator diff
                    }
                    a.size - b.size
                }
        )
        return seam
    }

    /**
     * Returns the maximum encoded literal byte length across all registered secrets.
     *
     * Used by [StreamingRedactor] to bound the pending buffer and ensure enough
     * lookahead exists to rule out any secret match before emitting a byte.
     *
     * When no secrets are registered, returns [MIN_SECRET_WINDOW] (a safe floor).
     *
     * @return Maximum literal byte length, floored at [MIN_SECRET_WINDOW]
     */
    internal fun maxLiteralByteLength(): Int {
        if (registeredSecrets.isEmpty()) return MIN_SECRET_WINDOW

        var maxLen = 0
        for (secret in registeredSecrets) {
            for (variant in generateEncodedVariants(secret)) {
                maxLen = maxOf(maxLen, variant.toByteArray(Charsets.UTF_8).size)
            }
        }
        return maxOf(maxLen, MIN_SECRET_WINDOW)
    }

    /**
     * Returns the number of registered secrets.
     */
    fun size(): Int = registeredSecrets.size

    /**
     * Computes the rolling secret-window size for [StreamingRedactor].
     *
     * The window equals `max(generatedPatternLiteralLength) - 1` over all
     * registered secrets and all encoding variants. Uses the SAME [generateEncodedVariants]
     * seam as [buildActivePatterns] to ensure consistent enumeration without duplication.
     *
     * Per [StreamingRedactor] design §Byte-window redaction algorithm:
     * - `secret_window = max(registeredPatternLiteralLength) - 1`
     * - `buffer capacity = secret_window + chunkSize`
     *
     * The floor is 7 bytes: the shortest registered secret is 8 bytes
     * ([MIN_MASKABLE_LENGTH]), and hex encoding of 8 bytes yields 16 chars,
     * so `16 - 1 = 15`. If no secrets are registered, a default window
     * of 7 is returned (enough to catch any split match of the minimum
     * pattern size).
     *
     * @return the maximum encoded pattern literal length minus 1, floored at 7
     */
    internal fun maxPatternLength(): Int {
        if (registeredSecrets.isEmpty()) return MIN_SECRET_WINDOW

        var maxLen = 0
        for (secret in registeredSecrets) {
            for (variant in generateEncodedVariants(secret)) {
                maxLen = maxOf(maxLen, variant.length)
            }
        }

        return maxOf(maxLen - 1, MIN_SECRET_WINDOW)
    }

    /**
     * Builds the URL-encoded variant of a secret.
     * Returns empty string if no special chars requiring encoding are present.
     */
    private fun buildUrlEncodedVariant(secret: String): String {
        val sb = StringBuilder()
        for (ch in secret) {
            URL_ENCODE_CHARS[ch]?.let { encoded ->
                sb.append(encoded)
            }
        }
        return sb.toString()
    }

    /**
     * Scrubs all registered secret patterns from a string.
     *
     * This is a standalone scrub for use cases like [GitCheckoutFailed.reason]
     * where the error message may contain embedded credentials that need to be
     * redacted before the event is emitted.
     *
     * INV-L6-CR-013: `GitCheckoutFailed.reason` must be scrubbed via this method
     * before construction of the event.
     *
     * @param input The string to scrub
     * @return The scrubbed string with all registered secrets replaced by "****"
     */
    fun scrub(input: String): String {
        val patterns = buildActivePatterns()
        if (patterns.isEmpty()) return input

        var result = input
        for (pattern in patterns) {
            result = pattern.replace(result, SCRUB_MARKER)
        }
        return result
    }

    companion object {
        /**
         * GitLab minimum maskable secret length.
         * Secrets below this threshold are NOT registered for masking.
         */
        const val MIN_MASKABLE_LENGTH = 8

        /**
         * Default minimum secret window for [StreamingRedactor].
         *
         * Floor: the shortest registered secret is 8 bytes ([MIN_MASKABLE_LENGTH]);
         * hex encoding doubles this to 16 chars; `16 - 1 = 15`. If no secrets are
         * registered, this floor ensures the redactor can still process chunks
         * without under-running the buffer.
         */
        const val MIN_SECRET_WINDOW = 7

        /**
         * Marker used to replace scrubbed secret values.
         */
        const val SCRUB_MARKER = "****"

        /**
         * URL-encodes a string for the common special chars in secrets.
         */
        private val URL_ENCODE_CHARS = mapOf(
            '+' to "%2B",
            '/' to "%2F",
            '=' to "%3D",
            '&' to "%26",
            '%' to "%25",
            '?' to "%3F",
            '#' to "%23",
            '@' to "%40",
            '!' to "%21",
            '$' to "%24",
            '\'' to "%27",
            '"' to "%22",
            ' ' to "%20"
        )
    }
}

/**
 * Warning event emitted when a short secret is not registered for masking.
 *
 * @param credentialsId The credential ID that was not masked
 * @param length The actual length of the secret value
 */
data class SecretShorterThanMinimumMaskableLengthWarning(
    val credentialsId: String,
    val length: Int,
)
