plugins {
    kotlin("jvm")
}

dependencies {
    implementation(project(":pipeline-domain"))
    implementation(project(":pipeline-events"))
    implementation(project(":pipeline-credentials-api"))
    implementation(project(":pipeline-step-sdk:api"))
    implementation(project(":pipeline-step-sdk:runtime"))
    implementation(project(":pipeline-scripting-api"))
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.4")
}

tasks.test {
    useJUnitPlatform()
}

group = "dev.rubentxu.pipeline.v2"
version = "0.36.0"

kotlin {
    jvmToolchain(21)
    compilerOptions {
        languageVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0)
        apiVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0)
    }
}

// ----------------------------------------------------------------------------
// SCM/Git OFFICIAL_PLUGIN provenance seam (LFC-2E2 / F5.1 / ADR-0092).
//
// The contributor (ScmGitStepDefinitionContributor) refuses to register
// without the real SHA-256 of its own artefact — that is the "no
// fabricated SHA" contract the human reviewer asked for.
//
// We compute the digest at build time by streaming the contents of every
// class file produced by `compileKotlin` and every resource processed by
// `processResources` through `sha256sum` (always present on Linux) and
// then taking the SHA-256 of the concatenation. The resulting digest is
// deterministic for a given module source revision (same source -> same
// classes -> same digest) and is independent of the JAR layout / packaging
// timestamp — a much stronger provenance than hashing the JAR bytes would
// give us (since `Built-Date` and `Built-By` would randomise the JAR).
//
// The digest is written to `META-INF/scm-git-release.properties` so it
// ships inside the JAR and is observable by any consumer.
//
// If the digest cannot be computed (no compiled classes yet — e.g. when
// running compileKotlin directly), the properties file is left absent
// and the contributor fails closed at registration time with a clear
// diagnostic. A canonical build ALWAYS goes through `classes` first.
// ----------------------------------------------------------------------------

val scmGitPublisher = providers.gradleProperty("pipeline.scm-git.publisher").orElse("pipeline-kotlin")
val scmGitNamespace = providers.gradleProperty("pipeline.scm-git.namespace").orElse("pipeline.scm-git")
val scmGitVersion = providers.gradleProperty("pipeline.scm-git.release.version").orElse(version.toString())

val scmGitReleaseProps = layout.buildDirectory.file("resources/main/META-INF/scm-git-release.properties")

val computeScmGitDigest = tasks.register<Exec>("computeScmGitDigest") {
    group = "scm-git"
    description = "Compute the SCM/Git OFFICIAL_PLUGIN provenance SHA-256 (deterministic over class files + resources)."

    val publisher = scmGitPublisher
    val namespace = scmGitNamespace
    val ver = scmGitVersion

    // We declare `outputs.file` only (no input snapshot), because the
    // input tree is generated by Kotlin compilation and changes
    // incrementally. Relying on inputs.dir + skipWhenEmpty made Gradle
    // mark this task NO-SOURCE on incremental builds; declaring only an
    // output keeps the task always-running and idempotent (overwrites
    // the file with the same content if the inputs are unchanged).
    outputs.file(scmGitReleaseProps)

    dependsOn("compileKotlin", "processResources")

    doFirst {
        val classesDir = layout.buildDirectory.dir("classes/kotlin/main").get().asFile
        require(classesDir.exists()) { "classes/kotlin/main does not exist: run compileKotlin first" }
        val resourcesDir = layout.buildDirectory.dir("resources/main").get().asFile
        val out = scmGitReleaseProps.get().asFile
        out.parentFile.mkdirs()
        // Exclude the provenance file itself from the hash input — we
        // are computing the digest of OUR CONTENTS, and including the
        // provenance file would create a chicken-and-egg that shifts
        // the digest between runs (verified empirically before this
        // exclusion).
        val excludedOutput = out.absolutePath
        val classFiles: List<String> = classesDir.walkTopDown()
            .filter { it.isFile && it.absolutePath != excludedOutput }
            .map { it.absolutePath }
            .toList()
            .sorted()
        val resourceFiles: List<String> = if (resourcesDir.exists()) {
            resourcesDir.walkTopDown()
                .filter { it.isFile && it.absolutePath != excludedOutput }
                .map { it.absolutePath }
                .toList()
                .sorted()
        } else {
            emptyList()
        }
        val all = (classFiles + resourceFiles).joinToString(" ")
        require(all.isNotEmpty()) { "No class or resource files to hash for SCM/Git OFFICIAL_PLUGIN provenance" }
        commandLine = listOf("sh", "-c", "sha256sum $all | sha256sum | awk '{print $1}' > '${out.absolutePath}.digest'")
    }

    doLast {
        val out = scmGitReleaseProps.get().asFile
        val digestFile = File("${out.absolutePath}.digest")
        val hex = digestFile.readText().trim()
        require(hex.length == 64) { "Expected 64-hex SHA-256, got '${hex.take(80)}'" }
        val digest = "sha256:$hex"
        out.writeText(
            buildString {
                appendLine("pipeline.scm-git.publisher=${publisher.get()}")
                appendLine("pipeline.scm-git.namespace=${namespace.get()}")
                appendLine("pipeline.scm-git.release.version=${ver.get()}")
                appendLine("pipeline.scm-git.release.digest=$digest")
                appendLine("pipeline.scm-git.module=scm-git")
            },
        )
        digestFile.delete()
        println("scm-git: provenance written to $out (digest=${digest.take(20)}...)")
    }
}

tasks.named("jar") {
    // The JAR must include the provenance file. `processResources` depends
    // on `computeScmGitDigest` (Gradle's processResources is a copy task
    // and so the runtime ordering naturally picks the file up). We
    // declare an explicit dependsOn for clarity even though Gradle's
    // default lifecycle would handle it.
    dependsOn(computeScmGitDigest)
}

// Forward the release properties as system properties to every Test task so
// the contributor can read them via System.getProperty at class load (the
// contributor is invoked during tests, not during compilation). We
// deliberately do NOT inline them in the source: the contributor reads from
// the artefact tree, not from build-config-time source.
val scmGitReleasePropsFile = scmGitReleaseProps

fun loadPropsAsMap(file: File): Map<String, String> {
    if (!file.exists()) return emptyMap()
    val map = linkedMapOf<String, String>()
    file.useLines { lines ->
        for (line in lines) {
            val trimmed = line.trim()
            if (trimmed.isEmpty() || trimmed.startsWith("#")) continue
            val idx = trimmed.indexOf('=')
            if (idx > 0) {
                val k = trimmed.substring(0, idx).trim()
                val v = trimmed.substring(idx + 1).trim()
                map[k] = v
            }
        }
    }
    return map
}

tasks.withType<Test>().configureEach {
    val props = loadPropsAsMap(scmGitReleasePropsFile.get().asFile)
    if (props.isNotEmpty()) {
        for ((k, v) in props) systemProperty(k, v)
        systemProperty("pipeline.scm-git.release.digest.missing", "false")
    } else {
        systemProperty("pipeline.scm-git.release.digest", "sha256:" + "0".repeat(64))
        systemProperty("pipeline.scm-git.release.version", scmGitVersion.get())
        systemProperty("pipeline.scm-git.publisher", scmGitPublisher.get())
        systemProperty("pipeline.scm-git.namespace", scmGitNamespace.get())
        systemProperty("pipeline.scm-git.release.digest.missing", "true")
    }
}
