import java.io.ByteArrayOutputStream
import java.security.MessageDigest

/**
 * The one hashing primitive the provenance seam uses.
 *
 * `sha256sum` is not reachable from here without a shell, and a shell is what made the digest
 * path-dependent in the first place (see AUD-01 in `computeScmGitDigest`).
 */
fun sha256Hex(bytes: ByteArray): String =
    MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

plugins {
    kotlin("jvm")
}

dependencies {
    implementation(project(":pipeline-domain"))
    implementation(project(":pipeline-events"))
    implementation(project(":pipeline-credentials-api"))
    implementation(project(":pipeline-step-sdk:api"))
    implementation(project(":pipeline-step-sdk:runtime"))
    implementation(project(":pipeline-scripting-api"))
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.4")
}

tasks.test {
    useJUnitPlatform()
}

group = "dev.rubentxu.pipeline.v2"
version = "0.36.0"

kotlin {
    jvmToolchain(21)
    compilerOptions {
        languageVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0)
        apiVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0)
    }
}

// ----------------------------------------------------------------------------
// SCM/Git OFFICIAL_PLUGIN provenance seam (LFC-2E2 / F5.1 / ADR-0092).
//
// The contributor (ScmGitStepDefinitionContributor) refuses to register
// without the real SHA-256 of its own artefact — that is the "no
// fabricated SHA" contract the human reviewer asked for.
//
// We compute the digest at build time by streaming the contents of every
// class file produced by `compileKotlin` and every resource processed by
// `processResources` through `sha256sum` (always present on Linux) and
// then taking the SHA-256 of the concatenation. The resulting digest is
// deterministic for a given module source revision (same source -> same
// classes -> same digest) and is independent of the JAR layout / packaging
// timestamp — a much stronger provenance than hashing the JAR bytes would
// give us (since `Built-Date` and `Built-By` would randomise the JAR).
//
// The digest is written to `META-INF/scm-git-release.properties` so it
// ships inside the JAR and is observable by any consumer.
//
// If the digest cannot be computed (no compiled classes yet — e.g. when
// running compileKotlin directly), the properties file is left absent
// and the contributor fails closed at registration time with a clear
// diagnostic. A canonical build ALWAYS goes through `classes` first.
// ----------------------------------------------------------------------------

val scmGitPublisher = providers.gradleProperty("pipeline.scm-git.publisher").orElse("pipeline-kotlin")
val scmGitNamespace = providers.gradleProperty("pipeline.scm-git.namespace").orElse("pipeline.scm-git")
val scmGitVersion = providers.gradleProperty("pipeline.scm-git.release.version").orElse(version.toString())

val scmGitReleaseProps = layout.buildDirectory.file("resources/main/META-INF/scm-git-release.properties")

val computeScmGitDigest = tasks.register("computeScmGitDigest") {
    group = "scm-git"
    description = "Compute the SCM/Git OFFICIAL_PLUGIN provenance SHA-256 (deterministic over class files + resources)."

    val publisher = scmGitPublisher
    val namespace = scmGitNamespace
    val ver = scmGitVersion

    // We declare `outputs.file` only (no input snapshot), because the
    // input tree is generated by Kotlin compilation and changes
    // incrementally. Relying on inputs.dir + skipWhenEmpty made Gradle
    // mark this task NO-SOURCE on incremental builds; declaring only an
    // output keeps the task always-running and idempotent (overwrites
    // the file with the same content if the inputs are unchanged).
    outputs.file(scmGitReleaseProps)

    dependsOn("compileKotlin", "processResources")

    // AUD-01: this used to be `sh -c "sha256sum <ABSOLUTE PATHS> | sha256sum"`, and `sha256sum`
    // PRINTS THE FILENAME IT WAS GIVEN. Two checkouts of identical bytes therefore produced
    // different digests, and the unquoted expansion broke outright on any path containing a space.
    // Measured on this host before the change (same bytes, two directories):
    //
    //   absolute paths   checkoutA 6d938320...  checkoutB c8b614a5...   <-- differs
    //   relative paths   checkoutA 666f3d32...  checkoutB 666f3d32...   <-- identical
    //
    // The digest is the plugin's provenance identity: a receipt that binds a candidate to a SHA
    // cannot prove anything if the same tree hashes differently depending on where it was checked
    // out. No shell is involved any more, so there is nothing to quote and nothing to inject.
    //
    // ONE hook, not doFirst-then-doLast: the previous shape passed the hex through a `.digest`
    // side file that doFirst wrote and doLast read and deleted, which is mutable state between two
    // hooks for no reason once the shell is gone.
    doLast {
        val classesDir = layout.buildDirectory.dir("classes/kotlin/main").get().asFile
        require(classesDir.exists()) { "classes/kotlin/main does not exist: run compileKotlin first" }
        val resourcesDir = layout.buildDirectory.dir("resources/main").get().asFile
        val out = scmGitReleaseProps.get().asFile
        out.parentFile.mkdirs()
        // The provenance file itself is EXCLUDED EXPLICITLY. Measured, not reasoned: leaving it
        // in made the digest change on every run, because the previous run's own output sits
        // under resources/main and is hashed into the next digest. The old code excluded it by
        // comparing absolute paths; a relative-path manifest compares the RELATIVE path instead.
        // Both the properties file and any leftover `.digest` side file from the pre-AUD-01 shell
        // pipeline are excluded, or stale state from an earlier checkout would still move the hash.
        val roots = listOf(classesDir to "classes") +
            listOfNotNull(resourcesDir.takeIf { it.exists() }?.let { it to "resources" })
        val entries = roots.flatMap { (root, prefix) ->
            root.walkTopDown().filter { it.isFile && it.path != out.path && it.name != out.name + ".digest" }.map { file ->
                "$prefix/${root.toPath().relativize(file.toPath()).toString().replace('\\', '/')}" to file.readBytes()
            }
        }.sortedBy { it.first }
        require(entries.isNotEmpty()) { "No class or resource files to hash for SCM/Git OFFICIAL_PLUGIN provenance" }
        val hex = sha256Hex(
            entries.joinToString("\n") { (rel, bytes) -> "${sha256Hex(bytes)}  $rel" }
                .toByteArray(Charsets.UTF_8),
        )
        require(hex.length == 64) { "Expected 64-hex SHA-256, got '${hex.take(80)}'" }
        val digest = "sha256:$hex"
        out.writeText(
            buildString {
                appendLine("pipeline.scm-git.publisher=${publisher.get()}")
                appendLine("pipeline.scm-git.namespace=${namespace.get()}")
                appendLine("pipeline.scm-git.release.version=${ver.get()}")
                appendLine("pipeline.scm-git.release.digest=$digest")
                appendLine("pipeline.scm-git.module=scm-git")
            },
        )
        println("scm-git: provenance written to $out (digest=${digest.take(20)}...)")
    }
}

tasks.named("jar") {
    // The JAR must include the provenance file. `processResources` depends
    // on `computeScmGitDigest` (Gradle's processResources is a copy task
    // and so the runtime ordering naturally picks the file up). We
    // declare an explicit dependsOn for clarity even though Gradle's
    // default lifecycle would handle it.
    dependsOn(computeScmGitDigest)
}

// Forward the release properties as system properties to every Test task so
// the contributor can read them via System.getProperty at class load (the
// contributor is invoked during tests, not during compilation). We
// deliberately do NOT inline them in the source: the contributor reads from
// the artefact tree, not from build-config-time source.
val scmGitReleasePropsFile = scmGitReleaseProps

fun loadPropsAsMap(file: File): Map<String, String> {
    if (!file.exists()) return emptyMap()
    val map = linkedMapOf<String, String>()
    file.useLines { lines ->
        for (line in lines) {
            val trimmed = line.trim()
            if (trimmed.isEmpty() || trimmed.startsWith("#")) continue
            val idx = trimmed.indexOf('=')
            if (idx > 0) {
                val k = trimmed.substring(0, idx).trim()
                val v = trimmed.substring(idx + 1).trim()
                map[k] = v
            }
        }
    }
    return map
}

tasks.withType<Test>().configureEach {
    val props = loadPropsAsMap(scmGitReleasePropsFile.get().asFile)
    if (props.isNotEmpty()) {
        for ((k, v) in props) systemProperty(k, v)
        systemProperty("pipeline.scm-git.release.digest.missing", "false")
    } else {
        systemProperty("pipeline.scm-git.release.digest", "sha256:" + "0".repeat(64))
        systemProperty("pipeline.scm-git.release.version", scmGitVersion.get())
        systemProperty("pipeline.scm-git.publisher", scmGitPublisher.get())
        systemProperty("pipeline.scm-git.namespace", scmGitNamespace.get())
        systemProperty("pipeline.scm-git.release.digest.missing", "true")
    }
}


// ----------------------------------------------------------------------------
// S6/C — the manifest DOCUMENT, derived from the code, not typed by hand.
//
// The declaration object is the one authority: the contributor reads it at runtime
// and this task reads it at build time. Typing the JSON here instead would create a
// second authority able to describe Steps the code does not have.
//
// The digest task MUST run first: the manifest reports the digest and fails closed
// for lack of provenance. The declared digest covers the artifact content EXCLUDING
// this document, the same convention the release-properties file already uses.
// ----------------------------------------------------------------------------

val scmGitManifest = layout.buildDirectory.file("resources/main/META-INF/pipelinek/plugin-manifest.json")

val emitScmGitManifest = tasks.register<JavaExec>("emitScmGitManifest") {
    group = "scm-git"
    description = "S6/C: emit the machine-readable plugin manifest into the artifact."

    dependsOn(computeScmGitDigest)
    mainClass.set("dev.rubentxu.pipeline.v2.sdk.scm.git.step.ScmGitPluginDeclarationKt")

    // The main reads its release properties off ITS OWN classpath, so the freshly
    // generated resources directory has to be on it.
    classpath = sourceSets["main"].runtimeClasspath + files(layout.buildDirectory.dir("resources/main"))

    inputs.files(scmGitReleaseProps)
    inputs.property("apiRange", "[0.47.0, 0.49.0)")
    outputs.file(scmGitManifest)

    val out = scmGitManifest
    val captured = ByteArrayOutputStream()
    standardOutput = captured

    doFirst {
        out.get().asFile.parentFile.mkdirs()
        // The buffer lives for the whole configuration, so a second execution in the
        // same build would APPEND to the first document and emit concatenated JSON.
        captured.reset()
    }

    doLast {
        val text = captured.toString(Charsets.UTF_8)
        if (text.isBlank()) {
            throw GradleException(
                "S6/C: manifest emission produced no output. The scm-git plugin would ship without " +
                    "META-INF/pipelinek/plugin-manifest.json and admission would refuse it at runtime.",
            )
        }
        out.get().asFile.writeText(text)
        println("scm-git: manifest emitted to " + out.get().asFile)
    }
}

tasks.named("processResources") {
    finalizedBy(emitScmGitManifest)
}

tasks.named("jar") {
    dependsOn(emitScmGitManifest)
}
